# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

from Core     import Request, Response
from .        import home_router
from Settings import PROJE

@home_router.get("/robots.txt")
async def robots_txt(request: Request):
    """robots.txt - Arama motoru botları için yönergeler"""

    robots = f"""# robots.txt for {PROJE}
# Generated by keyiflerolsun

# All bots welcome, except for paths listed below
User-agent: *
Disallow: /
"""

    return Response(
        content    = robots,
        media_type = "text/plain; charset=utf-8",
        headers    = {
            "Cache-Control" : "public, max-age=86400",
            "X-Robots-Tag"  : "noindex"
        }
    )

@home_router.get("/.well-known/security.txt")
@home_router.get("/security.txt")
async def security_txt(request: Request):
    """security.txt - Güvenlik açıklarını bildirmek için iletişim bilgileri"""

    security = f"""# Security Policy for {PROJE}

Contact: mailto:keyiflerolsun@gmail.com
Expires: {str(__import__('datetime').datetime.now(__import__('datetime').timezone.utc) + __import__('datetime').timedelta(days=365))[:10]}T23:59:59.000Z
Preferred-Languages: tr, en
Canonical: https://{request.url.netloc}/.well-known/security.txt

# Güvenlik açığı bildirimi için lütfen yukarıdaki e-posta adresini kullanın.
# Security vulnerability reports should be sent to the email above.
"""

    return Response(
        content    = security,
        media_type = "text/plain; charset=utf-8",
        headers    = {
            "Cache-Control" : "public, max-age=86400",
            "X-Robots-Tag"  : "noindex"
        }
    )
