# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

name: CapRover Yükleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master

jobs:
  CapRoverYukleyici:
    name   : Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Depo
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 2

      - name: Node.js Kurulumu
        uses: actions/setup-node@v6.4.0
        with:
          node-version: "22"

      - name: CapRover CLI Kurulumu
        run : npm i -g caprover

      - name: Değişiklik
        id  : degisiklik
        run : |
          # Stream (haric dışındaki dosyalar)
          if git diff --name-only HEAD^ | grep -vE '^haric/' | grep -qE '\.(py|toml|txt|j2|html|css|js|json|yaml|yml)$'; then
            echo "stream=true" >> $GITHUB_OUTPUT
          else
            echo "stream=false" >> $GITHUB_OUTPUT
          fi

      - name: Stream TarBall
        if  : steps.degisiklik.outputs.stream == 'true'
        uses: a7ul/tar-action@v1.2.0
        with:
          command: c
          cwd    : "./"
          files  : ./
          outPath: deploy.tar

      - name: Deploy
        if  : steps.degisiklik.outputs.stream == 'true'
        run : |
          caprover deploy --caproverUrl "${{ secrets.SERVER }}" \
          --appToken "${{ secrets.STREAM_TOKEN }}" \
          --appName " ${{ secrets.STREAM_APP }}" \
          --tarFile ./deploy.tar
